# Generated by Django 4.2.10 on 2024-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
