# Generated by Django 4.2.10 on 2024-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='small_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
