# Generated by Django 4.2.10 on 2024-05-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_small_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='small_title',
        ),
    ]
