# Generated by Django 4.2.10 on 2024-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blog_small_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='small_content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
