# Generated by Django 4.2.10 on 2024-05-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog_small_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='small_content',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
