# Generated by Django 4.2.10 on 2024-05-11 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lesson_course'),
        ('dashboard', '0009_courseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
