# Generated by Django 4.2.10 on 2024-05-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lesson_course'),
        ('dashboard', '0010_alter_courseprogress_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='last_accessed_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_accessed_lesson', to='courses.lesson'),
        ),
    ]
