# Generated by Django 4.2.10 on 2024-05-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lesson_course'),
        ('dashboard', '0011_alter_courseprogress_last_accessed_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_lessons', to='courses.lesson'),
        ),
    ]
