# Generated by Django 4.2.10 on 2024-05-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lesson_course'),
        ('dashboard', '0012_alter_courseprogress_completed_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='completed_lessons',
            field=models.ManyToManyField(related_name='completed_lessons', to='courses.lesson'),
        ),
    ]
