# Generated by Django 4.2.10 on 2024-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(default='course_default.jpg', upload_to='course_icons')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
