# Generated by Django 4.2.10 on 2024-05-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource',
            new_name='course_file',
        ),
    ]
