# Generated by Django 4.2.10 on 2024-05-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_resource_resource_course_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
